### ISSUE TITLE
プライバシーポリシーの記事を追加したい

### ISSUE THREAD

**Issue by nanophate** [animeoutreach/animeoutreach.org#1]
## やること

5月30日から新しい個人情報保護法が施工されると、5,000人未満であっても管理する義務がある。

https://www.clairlaw.jp/qa/cat446/post-90.html
http://www.gojo-partners.com/column-ps/1546/

参考にして欲しいサイトは以下になります。
どちらも信頼ができる会社と組織です
https://coderdojo.jp/docs/privacy
http://ocsi.org/tos/

そして、nondiscirmination policyの追加も必要だなっと思っています。
https://docs.google.com/document/d/1Whagw3J1sijN7X9ahih0aYFKd25gSaEh1XGAZ9s1x70/edit

雛形について

http://kiyaku.jp/hinagata/privacy.html

http://www.harm.jp/support001.html

**Comment by nanophate** [comment]
eitaさんが記事を描いてくれました！！
https://github.com/animeoutreach/animeoutreach.org/commit/e59a350eb4b23539787f1ff945c32346536d3a4b

**Comment by nanophate** [comment]
@uesakaeita http://kiyaku.jp/hinagata/gp.html
お手数ですが、時間があるときにこのひな形を使ってい問題ないか確認していただけませんか？
確認して欲しい内容は以下です

- [x] 弁護士や信頼できる内容なのか
- [ ] このひながたを使って私たちに問題はないか？(コピーライト的な意味) 
- [x] これを利用したと記載したほうがいいのか？

**Comment by uesakaeita** [comment]
了解しました！
明日の15時以降に対応していきます。

**Comment by uesakaeita** [comment]
11月11日、ラルフさんに確認した。

①ノーススターのサイトなどからも探してみる。　https://ridenorthstar.com/?lang=en

②栄太が全文確認する

③ラルフさんに最終確認をする

④なおやくんに伝える

**Comment by nanophate** [comment]
https://github.com/animeoutreach/animeoutreach.org/commit/79dae7ffc297c9be73a7baaecb60a3b4be2f51e4 こちらで追加されたので、クローズします。
