### ISSUE TITLE
ウェブサイトの細々な機能改善

### ISSUE THREAD

**Issue by nanophate** [animeoutreach/animeoutreach.org#4]
## やること

- [x] guestアカウントからみれない、ファイルがある "VISION"
- [x] memberで日本語の名前の人はリンクをクリックしてもページがない
- [x] 編集している画面が、Pageなのか、Layoutなのか、Blogなのかわかるようにする
    - [x] ~~pageで作ったはずなのに、ブログレイアウトになっているものがある~~

**Comment by nanophate** [comment]
> pageで作ったはずなのに、ブログレイアウトになっているものがある

上について調査してみましたが、問題が再現されませんでした💦
https://animeoutreach.slack.com/archives/C7W7D9L69/p1510069102000816
対応策として、ページを制作したさいにどのように見えるかを確認できるようにしたいとおもいます

**Comment by nanophate** [comment]
@uesakaeita 
時間がある時に、http://dev.animeoutreach.org で上にリストしている修正箇所が問題ないか確認して頂けると嬉しいです😉

**Comment by uesakaeita** [comment]
ごめんなさい、「上にリストしてある修正箇所」

**Comment by uesakaeita** [comment]
iPhoneから文章を書いてたら、途中で送信されてて、なぜかcloseしてしまってました。
変なところ押しちゃったのかも。

失礼しました。

**Comment by uesakaeita** [comment]
- [x] ゲストアカウントからは、pageの欄が見れない？

- [x] メールアドレスの変更

- [ ] ~~ドネーションの方法を追加する~~

- [ ] ~~メンバー募集・脚本チーム募集のpageを追加する~~

- [x] ファビコンの設定

**Comment by nanophate** [comment]
>  ゲストアカウントからは、pageの欄が見れない？

@uesakaeita ゲストアカウントから観れます。ロードが遅いみたいです。

**Comment by nanophate** [comment]
> メールアドレスの変更

https://github.com/animeoutreach/animeoutreach.org/commit/91f42b654b0f71f973184b1279a94db45b0649fe を `love`から`connect`に変更しました。

**Comment by nanophate** [comment]
> ドネーションの方法を追加する

ここのissueは機能改善なので、追加は #3 で行われると思います。
チェックマークはいれませんが、完了していることにします。

**Comment by nanophate** [comment]
> メンバー募集・脚本チーム募集のpageを追加する

以下のように細かく分けました。
こちらも機能改善ではなく追加のため

#6 メンバー募集
#7 脚本チーム募集

**Comment by nanophate** [comment]
> ファビコンの設定

@uesakaeita ☝️ の設定が終わりました！
以下で確認できます！

問題なければcloseしていただけると助かります🙏

https://realfavicongenerator.net/favicon_checker?protocol=http&site=dev.animeoutreach.org#.WgmQhLaB124

**Comment by uesakaeita** [comment]
ファビコンありがとう！

ゲストアカウントからpageが見れない…ロードを待っても出ないです。。。

タンブラーのサイトは残しておくの？

**Comment by uesakaeita** [comment]
サイトを開いてタブに出る、Middlemanというのは残るの？

**Comment by nanophate** [comment]
> ゲストアカウントからpageが見れない…ロードを待っても出ないです。。。

う〜ん、どうしてでしょう？
別のパソコンで試してもロードされました。

> タンブラーのサイトは残しておくの？

privacy policeが完成するまでは残します #8 

> サイトを開いてタブに出る、Middlemanというのは残るの？

admin画面に Middlemanって表示が出てます＾＾
ページによって変わります。

**Comment by nanophate** [comment]
修正を追加したので、一旦クローズします
